compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_multinode_launcher: standard
  gradient_accumulation_steps: 1
  offload_optimizer_device: none
  offload_param_device: none
  gradient_clipping: 1.0
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: no
fsdp_config: {}
machine_rank: ???
main_process_ip: ???
main_process_port: 1234
main_training_function: main
mixed_precision: fp16
num_machines: ???
num_processes: ???
use_cpu: false