train:
  seq_length: 550
  epochs: 10000
  total_steps: 6000
  batch_size: 4

  checkpoint_interval: 100000
  eval_interval: 400
  save_best: True
  checkpoint_dir: "/fsx/home-duyphung/all_checkpoints/pythia-1B-PPO-summ"

  pipeline: "PromptPipeline"
  trainer: "AcceleratePPOTrainer"

model:
  model_path: "pvduy/pythia-1B-sft-summarize-tldr"
  num_layers_unfrozen: 8

tokenizer:
  tokenizer_path: "EleutherAI/pythia-1.3b-deduped"
  truncation_side: "right"

optimizer:
  name: "adamw"
  kwargs:
    lr: 5.0e-6
    betas: [0.9, 0.999]
    eps: 1.0e-8
    weight_decay: 1.0e-6

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 1000000
    eta_min: 5.0e-6

method:
  name: "ppoconfig"
  num_rollouts: 128
  chunk_size: 4
  ppo_epochs: 4
  init_kl_coef: 0.1
  target: 6
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 1
  scale_reward: False
  ref_mean: null
  ref_std: null
  cliprange_reward: 10
  gen_kwargs:
    max_new_tokens: 50
    top_k: 0
    top_p: 1.0
    do_sample: True
    temperature: 1.0
