train:
  seq_length: 256
  epochs: 50
  total_steps: 100000
  batch_size: 4

  checkpoint_interval: 1000
  eval_interval: 500

  pipeline: "PromptPipeline"
  orchestrator: "PPOOrchestrator"
  trainer: "AcceleratePPOTrainer"

model:
  model_path: "/fsx/home-duyphung/models/litv2-6B-rev2/models--ChaiML--litv2-6B-rev2/snapshots/7033b427f06dc5115fe1d1dc8dfc5d9f79f5c2a9/"
  num_layers_unfrozen: 8

tokenizer:
  tokenizer_path: "/fsx/home-duyphung/models/litv2-6B-rev2/models--ChaiML--litv2-6B-rev2/snapshots/7033b427f06dc5115fe1d1dc8dfc5d9f79f5c2a9/"
  truncation_side: "left"

optimizer:
  name: "adamw"
  kwargs:
    lr: 5.0e-6
    betas: [0.9, 0.999]
    eps: 1.0e-8
    weight_decay: 0.01

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 100000
    eta_min: 5.0e-6

method:
  name: "ppoconfig"
  num_rollouts: 128
  chunk_size: 16
  ppo_epochs: 4
  init_kl_coef: 0.1
  target: 6
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 0.2
  scale_reward: False
  ref_mean: null
  ref_std: null
  cliprange_reward: 10
  gen_kwargs:
    max_new_tokens: 20
    do_sample: True
    top_k: 50
    temperature: 1.0
