model:
  model_path: "/fsx/home-duyphung/trlx/supervised_models/gpt2-supervised-summarize"  # Name of hf model to load
  tokenizer_path: "/fsx/home-duyphung/trlx/supervised_models/gpt2-xl"  # Name of hf tokenizer to load
  model_type: "AcceleratePPOModel"  # Name of accelerate model type to load
  num_layers_unfrozen: 8 #-1 # Number of bottom layers to freeze during training

train:
  seq_length: 550  # Size of LM context
  epochs: 25  # Train for max(epochs, total_steps)
  total_steps: 100000  # Train for max(epochs, total_steps)
  batch_size: 1  # batch size

  weight_decay: 1.0e-6 # weight decay param
  lr_init: 1.5e-5  # init learning rate
  lr_target: 1.5e-5  # target final learning rate
  opt_eps: 1.0e-8 
  opt_betas: [0.9, 0.95] # adam betas

  checkpoint_interval: 5000  # checkpoint interval
  eval_interval: 1000  # eval interval

  pipeline: "PPOPipeline"  # prompt pipeline to load
  orchestrator: "PPOOrchestrator"  # orchestrator to load

method:
  name: 'ppoconfig'  # Name of RL method config
  num_rollouts: 128 # Number of rollouts to collect per epoch
  chunk_size: 16  # Number of rollouts to collect in one loop of orchestrator
  ppo_epochs: 4  # Number of ppo epochs
  init_kl_coef: 0.2  # init kl coefficient
  target: 6  # target kl coefficient, set None for fixed kl coef
  horizon: 10000  # PPO horizon
  gamma: 1 # PPO discount
  lam: 0.95  # PPO lambda
  cliprange: 0.2  # clip range
  cliprange_value: 0.2  # clip range
  vf_coef: 0.2  # value term weight
  gen_kwargs:
    max_length: 550  # LM max sample gen length
    min_length: 550  # LM min sample gen length
    # top_k: 0.0  # top k
    # top_p: 1.0  # top p
    # do_sample: True  # sample
    # temperature: 0.3
